apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-io/platform-login-ui/docker-build:7.0.0-2310e9289cdeb681c55247963a8c8dcf2fee1749
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: platform-config
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: login-ui
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
